---
blank_issues_enabled: false
contact_links:
  - name: developer-portfolio Community Support
    url: https://github.com/ThunderBolt-OS/developer-portfolio/discussions
    about: Please ask and answer questions here.
